# Bootstrap:
#   docker-compose run --rm manage syncdb
#   docker-compose run --rm manage loaddata jwter/areas/fixtures/initial_data.json
#   docker-compose up -d django

version: '2'

services:
    django:
        build: .
        command: uwsgi --master --http :9000 --die-on-term --module django.core.wsgi:get_wsgi_application()
        environment:
            - DJANGO_SETTINGS_MODULE=jwter.settings
        volumes:
            - ./data:/mnt/data


    manage:
        extends: django
        entrypoint: python manage.py
        command: []
