version: '2'

services:
    django:
        # restart: unless-stopped
        volumes:
            - .:/app
        ports:
            # - "9000:9000"
            - "127.0.0.1:9000:9000"

    manage:
        volumes:
            - .:/app
