db:
    image: mysql
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=qweasdzxc
        - MYSQL_DATABASE=jwter
        - MYSQL_USER=jwter
        - MYSQL_PASSWORD=jwter
    volumes:
        - ./data:/var/lib/mysql

django:
    build: .
    command: ["python", "manage.py", "runfcgi", "method=prefork", "host=0.0.0.0", "port=9001", "daemonize=False"]
    restart: unless-stopped
    volumes:
        - ./media:/jwter-media
    #     - .:/app
    ports:
        - "127.0.0.1:9001:9001"
    links:
        - db
